### ISSUE TITLE
whether it can calculate the weighted SUR?

### ISSUE THREAD

**Issue by LfeiXie** [JanMarvin/nlsur#3]
As now, it's a package that like systemfit, well, I want to know how to implement a weighted SUR. It seemed more meaningful in the day of more accurate

**Comment by JanMarvin** [comment]
Hi @LfeiXie, thanks for your comment. Nlsur has an option for using weights. If you use weights, calculation is done using the Stata inspired way (e.g. no qrsolve). This should allow you to calculate a weighted nlsur.

Hope that helps
Marvin
