### ISSUE TITLE
nlsur seems to hang and not solve

### ISSUE THREAD

**Issue by AdamElderfield** [JanMarvin/nlsur#4]
Hi,

Thanks for the package. My issue is more than likely due to my problem, rather than an issue with the package. However, when I run nlsur it simply hangs, i.e. nothing happens but R is working (the little stop icon is present in the top corner of Rstudio). To investigate matters further, I put the max iteration to 1, rather to 1000, still the same issue. 

My model is a list of three equations as below:

equation_1
[1] "log((W*N)/Y) ~ log((THETA_BAR)) + ((1-a0sigma)/a0sigma)*(log(Y_norm/N_norm)-log(A)-a0gammal*(ti-to))"

$equation_2
[1] "log((R*K)/Y) ~ log((1-THETA_BAR)) + ((1-a0sigma)/a0sigma)*(log(Y_norm/K_norm)-log(A)-a0gammak*(ti-to))"

$equation_3
[1] "log(Y/N) ~ log((A*Ybar)/Nbar) + a0gammal*(ti-to) - ((1-a0sigma)/a0sigma)*log((1-THETA_BAR)*exp(((1-a0sigma)/a0sigma)*(a0gammal*(ti-to)-a0gammak*(ti-to)))*(K_norm/N_norm)^((a0sigma-1)/a0sigma) + THETA_BAR) "

`

where coefficients to be estimated are denoted a0xxx. Any ideas as to why this could be happening?

Thanks

Adam

**Comment by JanMarvin** [comment]
Hi Adam,

have you set trace = TRUE to see if anything's going on? If you've checked that nlsur itself works then the model might be the issue. You might vary the starting parameters or drop maybe equation 3 and see if that works).

Marvin

PS: another thing, nlsur adds every variable it cannot find in the data as variable. So you might look for typos.

**Comment by JanMarvin** [comment]
also you might be missing a few `*` in the above equations (e.g., R does not solve `WN` as `W*N`). edited: realized probably they are available just erased by the github issue markdown editor

**Comment by AdamElderfield** [comment]
I think you're correct, there absolutely should be be a multiplication there, something has happened with my equation parser ( I wirte the equations more naturally, but then parse them into something R can understand) I'll fix this and hopefully that fixes the issue!

Odd that it didn't give an error though?

Thanks for your help!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AdamElderfield** [comment]
I think the issue was the starting parameters I was feeding to the function had duplicates - I fixed that and the function works fine 👍 
Thanks again for your help!

**Comment by JanMarvin** [comment]
Glad that it's resolved! 

A bit of context: if your functions was missing any `*` the parameters are incorrectly guessed. let's say you wrote `WN` instead of `W*N`. in this case nlsur makes `WN` a parameter if no such variable is not found in the data.
